server:
  port: 8080

app:
  security:
    trust-inbound-headers: false
    public-routes:
      - "/v1/auth/**"
      - "/webhook/**"
      - "/actuator/**"
      
  rate-limit:
    method: fixed
    use-case:
      api-key:
        request-per-minute: 200

jwt:
  secret-key: don't-use-in-prodQHBHBSHSJNJnjdicjicdu487h4nf83uhu4

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: merchant-service
              url: ${MERCHANT_SERVICE_URI:lb://merchant-service}
              predicates:
                - Path=/v1/auth/**, /v1/merchants/**

            - id: payment-service
              url: ${PAYMENT_SERVICE_URI:lb://payment-service}
              predicates:
                - Path=/v1/orders/**, /v1/payments/**

            - id: vault-service
              url: ${VAULT_SERVICE_URI:lb://vault-service}
              predicates:
                - Path=/v1/vault/**

            - id: operation-service
              url: ${OPEARATION_SERVICE_URI:lb://operation-service}
              predicates:
                - Path=/webhook/**, 

---

spring:
  cloud:
    activate:
      on-profile: k8s

jwt:
  secret-key: ${JWT_SECRET}









                
