server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpay-merchant-db

jwt:
  secret-key: don't-use-in-prodQHBHBSHSJNJnjdicjicdu487h4nf83uhu4

webhook:
  secret-encryption-key: C/7uRXA+/w/Jj8XNPlAOWvCoBqr0Es0plZKvXr+UDqU=

---
spring:
  config:
    activate:
      on-profile: k8s
    datasource:
      url: jdbc:postgresql://postgres.razorpay-core.svc.cluster.local:5432/razorpay-merchant-db
      username: merchant_user
      password: ${MERCHANT_DB_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET}

webhook:
  secret-encryption-key: ${WEBHOOK_SECRET_ENCRYPTION_KEY}
