server:
  port: 9020

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpay-vault-db

vault:
  master-key: jA+rsAycq68ng3pyeIYG9UqIUuxSKCuIPZk25nc8UEA=

resilience4j:
  thread-pool-bulkhead:
  instances:
    vault-card-processor: 
      core-thread-pool-size: 5
      max-thread-pool-size: 10
      queue-capacity: 20
